#!/bin/bash

# Run opa tests on all policies - ignore these files/dirs
#OPA_TEST_COMMAND="opa test --ignore '.*','*.yml','*.yaml','Standards','sync_policies','test_policies' . -v"
# Run opa test using Docker
OPA_TEST_COMMAND="docker run -v ${PWD}:/policies --rm openpolicyagent/opa test /policies --ignore '.*','*.yml','*.yaml','Standards','sync_policies','test_policies' -v"


if TEST_RESULTS=$(eval "$OPA_TEST_COMMAND") ; then
    echo -e "\e[1;32m$TEST_RESULTS\e[0m" # Print test results in green
else
    echo -e "\e[1;31m$TEST_RESULTS\e[0m" # Print test results in red
    exit 2
fi